#+TITLE: Hot Cross Buns

* Hot Cross Buns

** Ingredients

*** Buns

- 1/4 cup (57g) apple juice or rum
- 1/2 cup (78g) dried fruit
- 1/2 cup (78g) raisins or dried currants
- 1 1/4 cups (283g) milk, room temperature
- 2 large eggs, plus 1 egg yolk (save the white for the topping)
- 6 tablespoons (85g) butter, at room temperature
- 2 teaspoons instant yeast
- 1/4 cup (53g) light brown sugar, packed
- 1 teaspoon cinnamon
- 1/4 teaspoon cloves or allspice
- 1/4 teaspoon nutmeg
- 1 3/4 teaspoons (11g) table salt
- 1 tablespoon baking powder
- 4 1/2 cups (540g) King Arthur Unbleached All-Purpose Flour

*** Topping

- 1 large egg white, reserved from above
- 1 tablespoon (14g) milk

*** Icing

- 1 cup plus 2 tablespoons (128g) confectioners' sugar
- 1/2 teaspoon King Arthur Pure Vanilla Extract
pinch of table salt
- 4 teaspoons milk, or enough to make a thick, pipeable icing

** Instructions

1. Lightly grease a 9" x 13" pan.
2. Mix the rum or apple juice with the dried fruit and raisins, cover with plastic wrap, and microwave briefly, just till the fruit and liquid are very warm, and the plastic starts to "shrink wrap" itself over the top of the bowl. Set aside to cool to room temperature. Note: If you worry about using plastic wrap in your microwave, simply cover the bowl with a glass lid.
3. Keep the fruit set aside. Weigh your flour; or measure it by gently spooning it into a cup, then sweeping off any excess. Mix together all of the remaining dough ingredients (including the eggs and the egg yolk from the separated egg). Knead the mixture, using an electric mixer or bread machine, until the dough is soft and elastic. It'll be very slack, sticking to the bottom of the bowl and your hands as you work with it (greasing your hands helps). Mix in the cooled fruit and any liquid not absorbed.
4. Let the dough rise for 1 hour, covered. It should become puffy, though may not double in bulk.
5. Divide the dough into billiard ball-sized pieces, about 3 3/4 ounces each. A heaped muffin scoop (about 1/3 cup) makes about the right portion. You'll make 12 to 14 buns. Use your greased hands to round them into balls. Arrange them in the prepared pan.
6. Cover the pan, and let the buns rise for 1 hour, or until they've puffed up and are touching one another. While the dough is rising, preheat the oven to 375°F.
7. Whisk together the reserved egg white and milk, and brush it over the buns.
8. Bake the buns for 20 minutes, until they're golden brown. Remove from the oven, carefully turn the buns out of the pan (they should come out in one large piece), and transfer them to a rack to cool.
9. Mix together the icing ingredients, and when the buns are completely cool, pipe it in a cross shape atop each bun.

** Riffs

- Want to make these buns a day or so ahead of time? Try the tangzhong technique, a Japanese method for increasing the softness and shelf life of yeast rolls. Begin by measuring out the flour and milk you’ll be using in the recipe. Now take 3 tablespoons of the measured flour and 1/2 cup of the measured milk; put them in a saucepan set over medium-high heat. Cook the mixture, whisking constantly, until it thickens and forms a thick slurry; this will take about 1 1/2 to 2 1/2 minutes. Transfer the cooked mixture to a bowl, let it cool to lukewarm, then combine it with the remaining flour, milk, and other dough ingredients. Proceed with the recipe as directed. Well-wrapped and stored at room temperature, your finished hot cross buns should stay soft and fresh for several days.
